services:
  backend:
    build: ./backend
    # ローカル用でコマンド上書き
    command: ${BACKEND_COMMAND}
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      DATABASE_HOST: ${DB_HOST}
      DATABASE_NAME: ${DB_NAME}
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8000:8000"
