# Generated by Django 5.2.15 on 2026-06-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_user_alter_todo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
